version: '2'

services:
  certbot:
    build: .
    container_name: certbot
    ports:
      - "443:443"
    volumes:
      - ./certs:/certs
      - ./letsencrypt:/etc/letsencrypt
    restart: always
    environment:
      #- WEBROOT=""
      - DEBUG=false
      - STAGING=true
      - DOMAINS=my.domain.com
      - EMAIL=user@my.domain.com
      - CONCAT=false
